apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafdrop.fullname" . }}
  labels:
        {{- include "kafdrop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.port }}
      targetPort: {{ .Values.service.port.targetPort }}
      name: {{ .Values.service.port.name }}
      protocol: {{ .Values.service.port.protocol }}
  selector:
    {{- include "kafdrop.selectorLabels" . | nindent 4 }}