replicaCount: 0

image:
  repository: "bitnami/elasticsearch"
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "default"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

env:
  discovery.type: single-node

service:
  port: 9200
  targetPort: 9200
  type: NodePort

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

volumeMounts: []

volumes: []