replicaCount: 1

image:
  repository: "obsidiandynamics/kafdrop"
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "default"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

env:
  KAFKA_BROKER_CONNECT: kafka-kafka:9092

service:
  port:
    port: 9000
    targetPort: 9000
    name: http-kafdrop
    protocol: TCP
  type: NodePort

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

volumeMounts: []

volumes: []

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: all-in-service.kafdrop.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kafka-kafdrop
              port:
                name: http-kafdrop
  tls: []