apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.configMapPrometheus" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.prometheusConfig }}
  {{ $key }}: |
{{ $value | nindent 4 }}
{{- end }}