apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.configMapInitDb" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configMapInitDb }}
  {{ $key }}: |
{{ $value | nindent 4 }}
{{- end }}