apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgresql.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgresql.serviceAccountName" . }}
      containers:
        - name: {{ include "postgresql.name" . }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: {{ .Values.secretData.user.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secret" . }}
                  key: {{ .Values.secretData.user.name }}
            - name: {{ .Values.secretData.password.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secret" . }}
                  key: {{ .Values.secretData.password.name }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.volume.postgresData.name }}
              mountPath: {{ .Values.volume.postgresData.mountPath }}
            - name: {{ .Values.volume.initScript.name }}
              mountPath: {{ .Values.volume.initScript.mountPath }}
      volumes:
        - name: {{ .Values.volume.postgresData.name }}
          persistentVolumeClaim:
            claimName: {{ include "postgresql.persistentVolumeClaim" . }}
        - name: {{ .Values.volume.initScript.name }}
          configMap:
            name: {{ include "postgresql.configMapInitDb" . }}