apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.persistentVolumeClaim" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  {{- with .Values.persistentVolumeClaim.accessModes }}
  accessModes:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}