apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secret" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
stringData:
  {{- range $k, $v := .Values.secretData }}
  {{ $v.name }}: {{ $v.value | quote }}
  {{- end }}